type: "openai"
args:
  api_name: "openai/gpt-4o-mini"
  api_key: "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"
  api_url: "https://openrouter.ai/api/v1"
run_args:
  temperature: 0.0
  max_tokens: 512
